# Generated by Django 5.0 on 2023-12-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapgrams', '0003_rename_blogpost_photopost'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
